remote_theme: pages-themes/midnight@v0.2.0
plugins: 
- jekyll-remote-theme
title: Azure VMWare Solution
author: Dennis Boeynaems
description: Stories from the trenches
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
